spring:
  application:
    name: eureka

server:
  port: 7001

eureka:

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      # 5 24
      defaultZone: http://localhost:7001/eureka/


